# Generated by Django 5.0.4 on 2024-04-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popalaz',
        ),
    ]
